package:
  name: open-vmdk
  version: "0.3.12"
  epoch: 0
  description: An assistant tool for creating Open Virtual Appliance (OVA).
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-pyyaml
      - py3-lxml
      - gnutar

environment:
  contents:
    packages:
      - build-base
      - zlib-dev
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vmware/open-vmdk.git
      tag: v${{package.version}}
      expected-commit: 7cbf0bb9ba8b69b8930907c8d44ec6eb2439bf91

  - name: Prepare open-vmdk build
    uses: autoconf/make

  - name: Build and install open-vmdk
    uses: autoconf/make-install
    with:
      opts: DESTDIR="${{targets.destdir}}"

subpackages:
  - name: open-vmdk-docs
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share "${{targets.subpkgdir}}"/usr/
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: vmware/open-vmdk
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
        - qemu-tools
  pipeline:
    - uses: test/tw/ldd-check

    - name: Verify open-vmdk
      runs: |
        set -euo pipefail

        qemu-img create -f raw /tmp/example.img 20M
        vmdk-convert /tmp/example.img /tmp/example.vmdk

        cat > /tmp/test.yaml <<EOF
        system:
            name: example
            type: vmx-17
            os_vmw: other4xLinux64Guest
            firmware: efi
            secure_boot: true
            default_configuration: grande

        networks:
            vm_network:
                name: "VM Network"
                description: "The VM Network network"

        hardware:
            cpus: 2
            memory: 2048
            sata1:
                type: sata_controller
            scsi1:
                type: scsi_controller
            cdrom1:
                type: cd_drive
                parent: sata1
            rootdisk:
                type: hard_disk
                parent: scsi1
                disk_image: /tmp/example.vmdk
            usb1:
                type: usb_controller
            ethernet1:
                type: ethernet
                subtype: VmxNet3
                network: vm_network
            videocard1:
                type: video_card
            vmci1:
                type: vmci

        configurations:
            tall:
                label: Tall
                description: too little for the money
            grande:
                label: Grande
                description: just right
            venti:
                label: Venti
                description: too much

        environment:
            transports:
                - com.vmware.guestInfo
                - iso
            categories:
                email: Email Settings
            properties:
                guestinfo.admin.email:
                    value: admin@company.org
                    user_configurable: true
                    type: string
                    description: "The Admin's email address"
                    label: "Email Address"
                    category: email

        extra_configs:
            feature.enabled:
                required: false
                value: true
            log.rotateSize:
                value: 2048000

        product:
            product: An Example VM
            vendor: A Company Inc.

        annotation:
            text: the password is top secret
        EOF

        ova-compose -i /tmp/test.yaml -o /tmp/test.ova
