package:
  name: squashfs-tools
  version: "4.7.4"
  epoch: 0
  description: A squashed read-only filesystem for Linux
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - build-base
      - zlib-dev
      - busybox
      - lz4-dev
      - lzo-dev
      - xz-dev
      - zstd-dev
      - sed
      - help2man

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/plougher/squashfs-tools.git
      tag: ${{package.version}}
      expected-commit: bad1d213ab6df587d6fa0ef7286180fbf7b86167

  - name: Prepare squashfs-tools build
    working-directory: /home/build/squashfs-tools
    uses: autoconf/make

  - pipeline:
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/local

  - name: Build and install squashfs-tools
    working-directory: /home/build/squashfs-tools
    uses: autoconf/make-install
    with:
      opts: CONFIG=1 INSTALL_PREFIX="${{targets.destdir}}"/usr/local

subpackages:
  - name: squashfs-tools-docs
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/local/man "${{targets.subpkgdir}}"/usr/share/
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: plougher/squashfs-tools

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - uses: test/tw/ldd-check

    - name: Verify squashfs-tools
      runs: |
        sqfstar -help-all
        sqfscat -help-all
        
        set -euo pipefail

        mkdir -p /tmp/sqfs-test/src
        echo "hello squashfs" > /tmp/sqfs-test/src/file1.txt
        printf "line1\nline2\n" > /tmp/sqfs-test/src/file2.txt
        mkdir -p /tmp/sqfs-test/src/subdir
        echo "inside subdir" > /tmp/sqfs-test/src/subdir/file3.txt
        cd /tmp/sqfs-test
        mksquashfs src image.sqfs
        unsquashfs -d extracted image.sqfs
        diff -r src extracted

        # gzip
        mksquashfs src img-gzip.sqfs -comp gzip
        unsquashfs -d out-gzip img-gzip.sqfs
        diff -r src out-gzip

        # lzo
        mksquashfs src img-lzo.sqfs -comp lzo
        unsquashfs -d out-lzo img-lzo.sqfs
        diff -r src out-lzo

        # lz4
        mksquashfs src img-lz4.sqfs -comp lz4
        unsquashfs -d out-lz4 img-lz4.sqfs
        diff -r src out-lz4

        # xz
        mksquashfs src img-xz.sqfs -comp xz
        unsquashfs -d out-xz img-xz.sqfs
        diff -r src out-xz

        # zstd
        mksquashfs src img-zstd.sqfs -comp zstd
        unsquashfs -d out-zstd img-zstd.sqfs
        diff -r src out-zstd
